"""Build map.js: a dot grid of the land and the lines where the plates meet.

The map is a flat grid of dots, one every STEP degrees, with every other row
nudged half a step so the dots sit in a honeycomb. This script marks each dot
as land or sea and packs the answers into a base64 bit string, and thins the
plate boundaries to a few thousand points, so the page carries its own map.

Sources:
  Natural Earth land, 1:50m (public domain), via the world-atlas package:
    curl -o land-50m.json https://cdn.jsdelivr.net/npm/world-atlas@2/land-50m.json
  Plate boundaries from Bird (2003), PB2002, via github.com/fraxen/tectonicplates (ODC-By):
    curl -o plates.json https://raw.githubusercontent.com/fraxen/tectonicplates/master/GeoJSON/PB2002_boundaries.json

  python3 tools/make-map.py land-50m.json plates.json > map.js
"""

import base64
import json
import sys

STEP = 0.75
NORTH, SOUTH = 84, -60
COLS = int(360 / STEP)
ROWS = int((NORTH - SOUTH) / STEP)
W, H = 2880, 1440  # equirectangular raster, 8 cells per degree


def decode_arcs(topology):
    scale = topology["transform"]["scale"]
    shift = topology["transform"]["translate"]
    arcs = []
    for arc in topology["arcs"]:
        x = y = 0
        points = []
        for dx, dy in arc:
            x += dx
            y += dy
            points.append((x * scale[0] + shift[0], y * scale[1] + shift[1]))
        arcs.append(points)
    return arcs


def ring_points(ring, arcs):
    points = []
    for index in ring:
        arc = arcs[index] if index >= 0 else arcs[~index][::-1]
        points.extend(arc if not points else arc[1:])
    return points


def rasterize(rings):
    """Even-odd scanline fill of every ring into a W x H grid of booleans."""
    grid = [bytearray(W) for _ in range(H)]
    edges = []
    for ring in rings:
        for (x1, y1), (x2, y2) in zip(ring, ring[1:] + ring[:1]):
            edges.append((x1, y1, x2, y2))
    for row in range(H):
        lat = 90 - (row + 0.5) * 180 / H
        crossings = []
        for x1, y1, x2, y2 in edges:
            if (y1 > lat) != (y2 > lat):
                crossings.append(x1 + (lat - y1) * (x2 - x1) / (y2 - y1))
        crossings.sort()
        for start, end in zip(crossings[0::2], crossings[1::2]):
            c0 = max(0, int((start + 180) * W / 360 + 0.5))
            c1 = min(W, int((end + 180) * W / 360 + 0.5))
            grid[row][c0:c1] = b"\x01" * max(0, c1 - c0)
    return grid


def land_bits(path):
    topology = json.load(open(path))
    arcs = decode_arcs(topology)
    rings = []
    for geometry in topology["objects"]["land"]["geometries"]:
        polygons = geometry["arcs"] if geometry["type"] == "MultiPolygon" else [geometry["arcs"]]
        for polygon in polygons:
            for ring in polygon:
                rings.append(ring_points(ring, arcs))
    grid = rasterize(rings)

    bits = bytearray((COLS * ROWS + 7) // 8)
    land = 0
    for j in range(ROWS):
        lat = NORTH - (j + 0.5) * STEP
        for i in range(COLS):
            lon = -180 + (i + 0.5 + (j % 2) * 0.5) * STEP
            lon = (lon + 180) % 360 - 180
            row = min(H - 1, int((90 - lat) * H / 180))
            col = min(W - 1, int((lon + 180) * W / 360))
            if grid[row][col]:
                n = j * COLS + i
                bits[n >> 3] |= 1 << (n & 7)
                land += 1
    return base64.b64encode(bits).decode(), land


def plate_lines(path):
    """Each boundary as a flat list of lon, lat in tenths of a degree, thinned to half a degree."""
    lines = []
    for feature in json.load(open(path))["features"]:
        geometry = feature["geometry"]
        parts = geometry["coordinates"] if geometry["type"] == "MultiLineString" else [geometry["coordinates"]]
        for part in parts:
            flat = []
            last = None
            for lon, lat in part:
                point = (round(lon * 2) * 5, round(lat * 2) * 5)
                if point != last:
                    flat.extend(point)
                    last = point
            if len(flat) >= 4:
                lines.append(flat)
    return lines


def main(land_path, plates_path):
    bits, land = land_bits(land_path)
    lines = plate_lines(plates_path)
    print("// Generated by tools/make-map.py from Natural Earth (public domain)")
    print("// and the PB2002 plate boundaries of Bird (2003).")
    print(f"// {land} of {COLS * ROWS} dots are land; {len(lines)} plate boundaries.")
    print(
        f"window.MAP = {{ step: {STEP}, north: {NORTH}, cols: {COLS}, rows: {ROWS}, "
        f'bits: "{bits}", plates: {json.dumps(lines, separators=(",", ":"))} }};'
    )


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
